//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lunchsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2NF_員工清單
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C2NF_員工清單()
        {
            this.C2NF_訂單細表 = new HashSet<C2NF_訂單細表>();
        }
    
        public int employee_id { get; set; }
        public string employee_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C2NF_訂單細表> C2NF_訂單細表 { get; set; }
    }
}
