//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lunchsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3NF_午餐種類
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C3NF_午餐種類()
        {
            this.C3NF_午餐 = new HashSet<C3NF_午餐>();
        }
    
        public int lunch_id { get; set; }
        public string lunch { get; set; }
        public Nullable<int> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C3NF_午餐> C3NF_午餐 { get; set; }
    }
}
