//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lunchsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3NF_午餐
    {
        public int detail_id { get; set; }
        public Nullable<int> master_id { get; set; }
        public Nullable<int> lunch_id { get; set; }
    
        public virtual C2NF_訂單細表 C2NF_訂單細表 { get; set; }
        public virtual C3NF_午餐種類 C3NF_午餐種類 { get; set; }
    }
}
